name: total_flutter
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.2
  collection: ^1.19.0
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.3.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.4.9
  shimmer: ^3.0.0
  provider: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  firebase_remote_config: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_icons:
  android: "launcher_icon" # Or "adaptive_icon" 
  ios: true
  image_path: "assets/bw_logo.png" # Path to your main icon asset
  # ... other options (min_sdk_android, adaptive_icon_background, etc.)