// import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:total_flutter/features/task_management/domain/models/task.dart';
import 'package:total_flutter/features/task_management/domain/models/task_list.dart';
import 'package:total_flutter/features/task_management/data/task_repository.dart';
import 'package:total_flutter/features/driver/data/driver_repository.dart';
import 'package:total_flutter/core/constants/app_constants.dart';
import 'package:total_flutter/core/utils/app_utils.dart';
// import 'package:total_flutter/core/utils/path_finding_utils.dart';
import 'package:total_flutter/core/widgets/modern_card.dart';

class TaskAssignmentScreen extends StatefulWidget {
  final TaskRepository taskRepository;
  final DriverRepository driverRepository;

  const TaskAssignmentScreen({
    super.key,
    required this.taskRepository,
    required this.driverRepository,
  });

  @override
  TaskAssignmentScreenState createState() => TaskAssignmentScreenState();
}

class TaskAssignmentScreenState extends State<TaskAssignmentScreen> {
  // final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final _formKey = GlobalKey<FormState>();

  final _nameController = TextEditingController();
  final _numberOfPalletsController = TextEditingController();
  final _estimatedTimeController = TextEditingController();
  String? _selectedSource;
  String? _selectedDestination;
  String _selectedTaskType = AppConstants.taskTypePickup;
  bool _isLoading = false;

  final List<String> _taskNames = TaskList.getTaskNames;

  @override
  void initState() {
    super.initState();
    // Initialize _selectedSource and _selectedDestination with default values
    // if (_taskNames.isNotEmpty) {
    //   _selectedSource = _taskNames.first;
    //   _selectedDestination = _taskNames.first;
    // }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _numberOfPalletsController.dispose();
    _estimatedTimeController.dispose();
    super.dispose();
  }

  Future<void> _assignTask() async {
    if (_formKey.currentState!.validate() &&
        _selectedSource != null &&
        _selectedDestination != null) {
      setState(() {
        _isLoading = true;
      });

      try {
        final currentUser = FirebaseAuth.instance.currentUser;
        final supervisorId = currentUser?.uid;
        if (supervisorId == null) {
          throw Exception('Supervisor not logged in');
        }

        final task = Task(
          id: '', // ID will be generated by Firestore
          name: _nameController.text,
          source: _selectedSource!,
          destination: _selectedDestination!,
          assignedDriver: null, // Will be assigned by Cloud Function
          createdBy: supervisorId, // Use ID instead of DocumentReference
          status: TaskStatus.pending,
          createdAt: DateTime.now(),
          type: _selectedTaskType,
          numberOfPallets: int.parse(_numberOfPalletsController.text),
          estimatedTime: int.parse(_estimatedTimeController.text),
          startTime: null,
          endTime: null,
          duration: 0,
          isQueued: false, // Will be determined by Cloud Function
        );

        await widget.taskRepository.createTask(task);

        if (!mounted) return;
        AppUtils.showSnackBar(
          context,
          AppConstants.successTaskCreated,
        );
        Navigator.pop(context);
      } catch (e) {
        if (!mounted) return;
        AppUtils.showSnackBar(
          context,
          '${AppConstants.errorTaskCreation}: $e',
          isError: true,
        );
      } finally {
        if (mounted) {
          setState(() {
            _isLoading = false;
          });
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Assign Task'),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                ModernCard(
                  margin: EdgeInsets.zero,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Task Details',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _nameController,
                        decoration: const InputDecoration(
                          labelText: 'Task Name',
                          border: OutlineInputBorder(),
                        ),
                        validator: AppUtils.validateRequired,
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        value: _selectedSource, // Can be null initially
                        decoration: const InputDecoration(
                          labelText: 'Source Location',
                          border: OutlineInputBorder(),
                        ),
                        hint: const Text('Select a source'), // Hint text
                        items: _taskNames
                            .map<DropdownMenuItem<String>>((String taskName) {
                          return DropdownMenuItem<String>(
                            value: taskName,
                            child: Text(taskName),
                          );
                        }).toList(),
                        onChanged: (value) {
                          setState(() {
                            _selectedSource = value; // Can be null
                          });
                        },
                        validator: AppUtils.validateRequired,
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        hint: Text('Select a destination'),
                        value: _selectedDestination,
                        decoration: const InputDecoration(
                          labelText: 'Destination Location',
                          border: OutlineInputBorder(),
                        ),
                        items: _taskNames
                            .map<DropdownMenuItem<String>>((String taskName) {
                          return DropdownMenuItem<String>(
                            value: taskName,
                            child: Text(taskName),
                          );
                        }).toList(),
                        onChanged: (value) {
                          setState(() {
                            _selectedDestination = value;
                          });
                        },
                        validator: AppUtils.validateRequired,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                ModernCard(
                  margin: EdgeInsets.zero,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Task Configuration',
                        style: Theme.of(context).textTheme.titleLarge,
                      ),
                      const SizedBox(height: 16),
                      DropdownButtonFormField<String>(
                        value: _selectedTaskType,
                        decoration: const InputDecoration(
                          labelText: 'Task Type',
                          border: OutlineInputBorder(),
                        ),
                        items: [
                          DropdownMenuItem(
                            value: AppConstants.taskTypePickup,
                            child: const Text('Pickup'),
                          ),
                          DropdownMenuItem(
                            value: AppConstants.taskTypeDelivery,
                            child: const Text('Delivery'),
                          ),
                          DropdownMenuItem(
                            value: AppConstants.taskTypeTransfer,
                            child: const Text('Transfer'),
                          ),
                        ],
                        onChanged: (value) {
                          setState(() {
                            _selectedTaskType = value!;
                          });
                        },
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _numberOfPalletsController,
                        decoration: const InputDecoration(
                          labelText: 'Number of Pallets',
                          border: OutlineInputBorder(),
                        ),
                        keyboardType: TextInputType.number,
                        validator: AppUtils.validateNumber,
                      ),
                      const SizedBox(height: 16),
                      TextFormField(
                        controller: _estimatedTimeController,
                        decoration: const InputDecoration(
                          labelText: 'Estimated Time (minutes)',
                          border: OutlineInputBorder(),
                        ),
                        keyboardType: TextInputType.number,
                        validator: AppUtils.validateNumber,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 24),
                SizedBox(
                  height: 50,
                  child: ElevatedButton(
                    onPressed: _isLoading ? null : _assignTask,
                    child: _isLoading
                        ? const CircularProgressIndicator()
                        : const Text('Assign Task'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
